server:
  port: 8083

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8081/oauth/token
      client-id: client-service
      client-secret: secret
      grant-type: client_credentials
